route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'
receivers:
  - name: 'email-notifications'
    email_configs:
    - to: naveenkumar@iplon.in,thamilarasan@iplon.in
      from: 
      smarthost: smtp.sendgrid.net:587
      auth_username: 
      auth_password: 
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
